// Code generated by protoc-gen-go. DO NOT EDIT.
// source: report2mail.proto

package proto

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type EmailToSend struct {
	EmailAddress         string   `protobuf:"bytes,1,opt,name=email_address,json=emailAddress,proto3" json:"email_address,omitempty"`
	Lastname             string   `protobuf:"bytes,2,opt,name=lastname,proto3" json:"lastname,omitempty"`
	Firstname            string   `protobuf:"bytes,3,opt,name=firstname,proto3" json:"firstname,omitempty"`
	Date                 string   `protobuf:"bytes,4,opt,name=date,proto3" json:"date,omitempty"`
	Office               string   `protobuf:"bytes,5,opt,name=office,proto3" json:"office,omitempty"`
	Filename             string   `protobuf:"bytes,6,opt,name=filename,proto3" json:"filename,omitempty"`
	PdfPayload           []byte   `protobuf:"bytes,7,opt,name=pdf_payload,json=pdfPayload,proto3" json:"pdf_payload,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EmailToSend) Reset()         { *m = EmailToSend{} }
func (m *EmailToSend) String() string { return proto.CompactTextString(m) }
func (*EmailToSend) ProtoMessage()    {}
func (*EmailToSend) Descriptor() ([]byte, []int) {
	return fileDescriptor_80f5e2b11758c811, []int{0}
}

func (m *EmailToSend) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EmailToSend.Unmarshal(m, b)
}
func (m *EmailToSend) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EmailToSend.Marshal(b, m, deterministic)
}
func (m *EmailToSend) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EmailToSend.Merge(m, src)
}
func (m *EmailToSend) XXX_Size() int {
	return xxx_messageInfo_EmailToSend.Size(m)
}
func (m *EmailToSend) XXX_DiscardUnknown() {
	xxx_messageInfo_EmailToSend.DiscardUnknown(m)
}

var xxx_messageInfo_EmailToSend proto.InternalMessageInfo

func (m *EmailToSend) GetEmailAddress() string {
	if m != nil {
		return m.EmailAddress
	}
	return ""
}

func (m *EmailToSend) GetLastname() string {
	if m != nil {
		return m.Lastname
	}
	return ""
}

func (m *EmailToSend) GetFirstname() string {
	if m != nil {
		return m.Firstname
	}
	return ""
}

func (m *EmailToSend) GetDate() string {
	if m != nil {
		return m.Date
	}
	return ""
}

func (m *EmailToSend) GetOffice() string {
	if m != nil {
		return m.Office
	}
	return ""
}

func (m *EmailToSend) GetFilename() string {
	if m != nil {
		return m.Filename
	}
	return ""
}

func (m *EmailToSend) GetPdfPayload() []byte {
	if m != nil {
		return m.PdfPayload
	}
	return nil
}

type SentStatus struct {
	Status               string   `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SentStatus) Reset()         { *m = SentStatus{} }
func (m *SentStatus) String() string { return proto.CompactTextString(m) }
func (*SentStatus) ProtoMessage()    {}
func (*SentStatus) Descriptor() ([]byte, []int) {
	return fileDescriptor_80f5e2b11758c811, []int{1}
}

func (m *SentStatus) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SentStatus.Unmarshal(m, b)
}
func (m *SentStatus) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SentStatus.Marshal(b, m, deterministic)
}
func (m *SentStatus) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SentStatus.Merge(m, src)
}
func (m *SentStatus) XXX_Size() int {
	return xxx_messageInfo_SentStatus.Size(m)
}
func (m *SentStatus) XXX_DiscardUnknown() {
	xxx_messageInfo_SentStatus.DiscardUnknown(m)
}

var xxx_messageInfo_SentStatus proto.InternalMessageInfo

func (m *SentStatus) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func init() {
	proto.RegisterType((*EmailToSend)(nil), "proto.EmailToSend")
	proto.RegisterType((*SentStatus)(nil), "proto.SentStatus")
}

func init() { proto.RegisterFile("report2mail.proto", fileDescriptor_80f5e2b11758c811) }

var fileDescriptor_80f5e2b11758c811 = []byte{
	// 239 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x4c, 0x90, 0xc1, 0x4a, 0x03, 0x31,
	0x10, 0x86, 0x59, 0x6d, 0x57, 0x77, 0xda, 0x1e, 0x3a, 0x07, 0x09, 0x45, 0xb0, 0x54, 0x0f, 0x3d,
	0xf5, 0xb0, 0x3e, 0x81, 0x88, 0x77, 0xd9, 0xed, 0xbd, 0x44, 0x33, 0x81, 0x85, 0x74, 0x13, 0x92,
	0x78, 0xf0, 0x41, 0x7d, 0x1f, 0xc9, 0x24, 0xba, 0x3d, 0x65, 0xbe, 0xef, 0x87, 0x19, 0xf2, 0xc3,
	0xda, 0x93, 0xb3, 0x3e, 0xb6, 0x67, 0x39, 0x98, 0x83, 0xf3, 0x36, 0x5a, 0x9c, 0xf3, 0xb3, 0xfb,
	0xa9, 0x60, 0xf1, 0x96, 0xf4, 0xd1, 0xf6, 0x34, 0x2a, 0x7c, 0x84, 0x15, 0x25, 0x3c, 0x49, 0xa5,
	0x3c, 0x85, 0x20, 0xaa, 0x6d, 0xb5, 0x6f, 0xba, 0x25, 0xcb, 0x97, 0xec, 0x70, 0x03, 0xb7, 0x46,
	0x86, 0x38, 0xca, 0x33, 0x89, 0x2b, 0xce, 0xff, 0x19, 0xef, 0xa1, 0xd1, 0x83, 0x2f, 0xe1, 0x35,
	0x87, 0x93, 0x40, 0x84, 0x99, 0x92, 0x91, 0xc4, 0x8c, 0x03, 0x9e, 0xf1, 0x0e, 0x6a, 0xab, 0xf5,
	0xf0, 0x49, 0x62, 0xce, 0xb6, 0x50, 0xba, 0xa2, 0x07, 0x43, 0xbc, 0xa8, 0xce, 0x57, 0xfe, 0x18,
	0x1f, 0x60, 0xe1, 0x94, 0x3e, 0x39, 0xf9, 0x6d, 0xac, 0x54, 0xe2, 0x66, 0x5b, 0xed, 0x97, 0x1d,
	0x38, 0xa5, 0xdf, 0xb3, 0xd9, 0x3d, 0x01, 0xf4, 0x34, 0xc6, 0x3e, 0xca, 0xf8, 0x15, 0xd2, 0x89,
	0xc0, 0x53, 0xf9, 0x4e, 0xa1, 0xf6, 0x15, 0x56, 0x1d, 0x37, 0x73, 0xb4, 0x5c, 0x02, 0xb6, 0xd0,
	0xa4, 0x1a, 0x32, 0x60, 0xae, 0xea, 0x70, 0xd1, 0xcf, 0x66, 0x5d, 0xdc, 0xb4, 0xfc, 0xa3, 0x66,
	0xf3, 0xfc, 0x1b, 0x00, 0x00, 0xff, 0xff, 0x57, 0xf4, 0x1e, 0x4f, 0x65, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ReportToEmailClient is the client API for ReportToEmail service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ReportToEmailClient interface {
	SendEmail(ctx context.Context, in *EmailToSend, opts ...grpc.CallOption) (*SentStatus, error)
}

type reportToEmailClient struct {
	cc *grpc.ClientConn
}

func NewReportToEmailClient(cc *grpc.ClientConn) ReportToEmailClient {
	return &reportToEmailClient{cc}
}

func (c *reportToEmailClient) SendEmail(ctx context.Context, in *EmailToSend, opts ...grpc.CallOption) (*SentStatus, error) {
	out := new(SentStatus)
	err := c.cc.Invoke(ctx, "/proto.ReportToEmail/SendEmail", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ReportToEmailServer is the server API for ReportToEmail service.
type ReportToEmailServer interface {
	SendEmail(context.Context, *EmailToSend) (*SentStatus, error)
}

// UnimplementedReportToEmailServer can be embedded to have forward compatible implementations.
type UnimplementedReportToEmailServer struct {
}

func (*UnimplementedReportToEmailServer) SendEmail(ctx context.Context, req *EmailToSend) (*SentStatus, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendEmail not implemented")
}

func RegisterReportToEmailServer(s *grpc.Server, srv ReportToEmailServer) {
	s.RegisterService(&_ReportToEmail_serviceDesc, srv)
}

func _ReportToEmail_SendEmail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EmailToSend)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReportToEmailServer).SendEmail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.ReportToEmail/SendEmail",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReportToEmailServer).SendEmail(ctx, req.(*EmailToSend))
	}
	return interceptor(ctx, in, info, handler)
}

var _ReportToEmail_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.ReportToEmail",
	HandlerType: (*ReportToEmailServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SendEmail",
			Handler:    _ReportToEmail_SendEmail_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "report2mail.proto",
}
